fix(gradle.yml): update test command to include test report publishing for improved visibility

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -18,7 +18,13 @@ jobs:
            run: ./gradlew jar
 
          - name: Run tests
-           run: ./gradlew test --stacktrace --info
+           run: ./gradlew test --tests "*"
+
+         - name: Publish Test Report
+           uses: mikepenz/action-junit-report@v5
+           if: success() || failure() # always run even if the previous step fails
+           with:
+              report_paths: "**/build/reports/tests/test/index.html"
 
          - name: Upload built jar file
            uses: actions/upload-artifact@v4
